#!/bin/bash

BDIR=$(cd $(dirname $0); pwd)


num_jars=$(ls "$BDIR"/core/target/scala-*/ | grep "gaea-core-assembly-.*.jar" | wc -l)

if [ "$num_jars" -eq "0" ]; then
    echo "Failed to find BMEG assembly" >&2
    echo "You need to build the GAEA tools with 'sbt/sbt assembly' before running this program." >&2
    exit 1
fi


GAEA_BUILD_JAR=`ls $BDIR/core/target/scala-*/gaea-core-assembly-*.jar | head -n1`
GAEA_MEM="-Xmx4g"
GAEA_BASE_CMD="java $GAEA_MEM -cp $GAEA_BUILD_JAR"

CMD=$1
shift

case $CMD in
load) $GAEA_BASE_CMD gaea.app.Import $@ ;;
esac