// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/src/main/proto/gaia/schema/GaiaSchema.proto

package gaia.schema;

public final class GaiaSchema {
  private GaiaSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VertexOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gaia.schema.Vertex)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string gid = 1;</code>
     */
    java.lang.String getGid();
    /**
     * <code>optional string gid = 1;</code>
     */
    com.google.protobuf.ByteString
        getGidBytes();

    /**
     * <code>optional string label = 2;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 2;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getProperties();
  }
  /**
   * Protobuf type {@code gaia.schema.Vertex}
   */
  public  static final class Vertex extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:gaia.schema.Vertex)
      VertexOrBuilder {
    // Use Vertex.newBuilder() to construct.
    private Vertex(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Vertex() {
      gid_ = "";
      label_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Vertex(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              gid_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                properties_ = com.google.protobuf.MapField.newMapField(
                    PropertiesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              properties = input.readMessage(
                  PropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              properties_.getMutableMap().put(properties.getKey(), properties.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gaia.schema.GaiaSchema.internal_static_gaia_schema_Vertex_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gaia.schema.GaiaSchema.internal_static_gaia_schema_Vertex_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gaia.schema.GaiaSchema.Vertex.class, gaia.schema.GaiaSchema.Vertex.Builder.class);
    }

    private int bitField0_;
    public static final int GID_FIELD_NUMBER = 1;
    private volatile java.lang.Object gid_;
    /**
     * <code>optional string gid = 1;</code>
     */
    public java.lang.String getGid() {
      java.lang.Object ref = gid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string gid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGidBytes() {
      java.lang.Object ref = gid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object label_;
    /**
     * <code>optional string label = 2;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>optional string label = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROPERTIES_FIELD_NUMBER = 3;
    private static final class PropertiesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  gaia.schema.GaiaSchema.internal_static_gaia_schema_Vertex_PropertiesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> properties_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetProperties() {
      if (properties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
     }
      return properties_;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getProperties() {
      return internalGetProperties().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, gid_);
      }
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, label_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetProperties().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        properties = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, properties);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, gid_);
      }
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, label_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetProperties().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        properties = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, properties);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static gaia.schema.GaiaSchema.Vertex parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gaia.schema.GaiaSchema.Vertex parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gaia.schema.GaiaSchema.Vertex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gaia.schema.GaiaSchema.Vertex parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gaia.schema.GaiaSchema.Vertex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gaia.schema.GaiaSchema.Vertex parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gaia.schema.GaiaSchema.Vertex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gaia.schema.GaiaSchema.Vertex parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gaia.schema.GaiaSchema.Vertex parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gaia.schema.GaiaSchema.Vertex parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gaia.schema.GaiaSchema.Vertex prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gaia.schema.Vertex}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gaia.schema.Vertex)
        gaia.schema.GaiaSchema.VertexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gaia.schema.GaiaSchema.internal_static_gaia_schema_Vertex_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gaia.schema.GaiaSchema.internal_static_gaia_schema_Vertex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gaia.schema.GaiaSchema.Vertex.class, gaia.schema.GaiaSchema.Vertex.Builder.class);
      }

      // Construct using gaia.schema.GaiaSchema.Vertex.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        gid_ = "";

        label_ = "";

        internalGetMutableProperties().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gaia.schema.GaiaSchema.internal_static_gaia_schema_Vertex_descriptor;
      }

      public gaia.schema.GaiaSchema.Vertex getDefaultInstanceForType() {
        return gaia.schema.GaiaSchema.Vertex.getDefaultInstance();
      }

      public gaia.schema.GaiaSchema.Vertex build() {
        gaia.schema.GaiaSchema.Vertex result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gaia.schema.GaiaSchema.Vertex buildPartial() {
        gaia.schema.GaiaSchema.Vertex result = new gaia.schema.GaiaSchema.Vertex(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.gid_ = gid_;
        result.label_ = label_;
        result.properties_ = internalGetProperties();
        result.properties_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gaia.schema.GaiaSchema.Vertex) {
          return mergeFrom((gaia.schema.GaiaSchema.Vertex)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gaia.schema.GaiaSchema.Vertex other) {
        if (other == gaia.schema.GaiaSchema.Vertex.getDefaultInstance()) return this;
        if (!other.getGid().isEmpty()) {
          gid_ = other.gid_;
          onChanged();
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        internalGetMutableProperties().mergeFrom(
            other.internalGetProperties());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gaia.schema.GaiaSchema.Vertex parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gaia.schema.GaiaSchema.Vertex) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object gid_ = "";
      /**
       * <code>optional string gid = 1;</code>
       */
      public java.lang.String getGid() {
        java.lang.Object ref = gid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGidBytes() {
        java.lang.Object ref = gid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gid = 1;</code>
       */
      public Builder setGid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gid = 1;</code>
       */
      public Builder clearGid() {
        
        gid_ = getDefaultInstance().getGid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gid = 1;</code>
       */
      public Builder setGidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 2;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> properties_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetProperties() {
        if (properties_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PropertiesDefaultEntryHolder.defaultEntry);
       }
        return properties_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableProperties() {
        onChanged();;
        if (properties_ == null) {
          properties_ = com.google.protobuf.MapField.newMapField(
              PropertiesDefaultEntryHolder.defaultEntry);
        }
        if (!properties_.isMutable()) {
          properties_ = properties_.copy();
        }
        return properties_;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String> getProperties() {
        return internalGetProperties().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableProperties() {
        return internalGetMutableProperties().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 3;</code>
       */
      public Builder putAllProperties(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableProperties().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gaia.schema.Vertex)
    }

    // @@protoc_insertion_point(class_scope:gaia.schema.Vertex)
    private static final gaia.schema.GaiaSchema.Vertex DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gaia.schema.GaiaSchema.Vertex();
    }

    public static gaia.schema.GaiaSchema.Vertex getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vertex>
        PARSER = new com.google.protobuf.AbstractParser<Vertex>() {
      public Vertex parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Vertex(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Vertex> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vertex> getParserForType() {
      return PARSER;
    }

    public gaia.schema.GaiaSchema.Vertex getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EdgeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gaia.schema.Edge)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string gid = 1;</code>
     */
    java.lang.String getGid();
    /**
     * <code>optional string gid = 1;</code>
     */
    com.google.protobuf.ByteString
        getGidBytes();

    /**
     * <code>optional string label = 2;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 2;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>optional string in = 3;</code>
     */
    java.lang.String getIn();
    /**
     * <code>optional string in = 3;</code>
     */
    com.google.protobuf.ByteString
        getInBytes();

    /**
     * <code>optional string out = 4;</code>
     */
    java.lang.String getOut();
    /**
     * <code>optional string out = 4;</code>
     */
    com.google.protobuf.ByteString
        getOutBytes();

    /**
     * <code>map&lt;string, string&gt; properties = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getProperties();
  }
  /**
   * Protobuf type {@code gaia.schema.Edge}
   */
  public  static final class Edge extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:gaia.schema.Edge)
      EdgeOrBuilder {
    // Use Edge.newBuilder() to construct.
    private Edge(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Edge() {
      gid_ = "";
      label_ = "";
      in_ = "";
      out_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Edge(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              gid_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              in_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              out_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                properties_ = com.google.protobuf.MapField.newMapField(
                    PropertiesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              properties = input.readMessage(
                  PropertiesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              properties_.getMutableMap().put(properties.getKey(), properties.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gaia.schema.GaiaSchema.internal_static_gaia_schema_Edge_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetProperties();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gaia.schema.GaiaSchema.internal_static_gaia_schema_Edge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gaia.schema.GaiaSchema.Edge.class, gaia.schema.GaiaSchema.Edge.Builder.class);
    }

    private int bitField0_;
    public static final int GID_FIELD_NUMBER = 1;
    private volatile java.lang.Object gid_;
    /**
     * <code>optional string gid = 1;</code>
     */
    public java.lang.String getGid() {
      java.lang.Object ref = gid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string gid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGidBytes() {
      java.lang.Object ref = gid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object label_;
    /**
     * <code>optional string label = 2;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>optional string label = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IN_FIELD_NUMBER = 3;
    private volatile java.lang.Object in_;
    /**
     * <code>optional string in = 3;</code>
     */
    public java.lang.String getIn() {
      java.lang.Object ref = in_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        in_ = s;
        return s;
      }
    }
    /**
     * <code>optional string in = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInBytes() {
      java.lang.Object ref = in_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        in_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OUT_FIELD_NUMBER = 4;
    private volatile java.lang.Object out_;
    /**
     * <code>optional string out = 4;</code>
     */
    public java.lang.String getOut() {
      java.lang.Object ref = out_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        out_ = s;
        return s;
      }
    }
    /**
     * <code>optional string out = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOutBytes() {
      java.lang.Object ref = out_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        out_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROPERTIES_FIELD_NUMBER = 5;
    private static final class PropertiesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  gaia.schema.GaiaSchema.internal_static_gaia_schema_Edge_PropertiesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> properties_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetProperties() {
      if (properties_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PropertiesDefaultEntryHolder.defaultEntry);
     }
      return properties_;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getProperties() {
      return internalGetProperties().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, gid_);
      }
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, label_);
      }
      if (!getInBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, in_);
      }
      if (!getOutBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, out_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetProperties().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        properties = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(5, properties);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, gid_);
      }
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, label_);
      }
      if (!getInBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, in_);
      }
      if (!getOutBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, out_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetProperties().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        properties = PropertiesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, properties);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static gaia.schema.GaiaSchema.Edge parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gaia.schema.GaiaSchema.Edge parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gaia.schema.GaiaSchema.Edge parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gaia.schema.GaiaSchema.Edge parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gaia.schema.GaiaSchema.Edge parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gaia.schema.GaiaSchema.Edge parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gaia.schema.GaiaSchema.Edge parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gaia.schema.GaiaSchema.Edge parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gaia.schema.GaiaSchema.Edge parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gaia.schema.GaiaSchema.Edge parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gaia.schema.GaiaSchema.Edge prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gaia.schema.Edge}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gaia.schema.Edge)
        gaia.schema.GaiaSchema.EdgeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gaia.schema.GaiaSchema.internal_static_gaia_schema_Edge_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableProperties();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gaia.schema.GaiaSchema.internal_static_gaia_schema_Edge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gaia.schema.GaiaSchema.Edge.class, gaia.schema.GaiaSchema.Edge.Builder.class);
      }

      // Construct using gaia.schema.GaiaSchema.Edge.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        gid_ = "";

        label_ = "";

        in_ = "";

        out_ = "";

        internalGetMutableProperties().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gaia.schema.GaiaSchema.internal_static_gaia_schema_Edge_descriptor;
      }

      public gaia.schema.GaiaSchema.Edge getDefaultInstanceForType() {
        return gaia.schema.GaiaSchema.Edge.getDefaultInstance();
      }

      public gaia.schema.GaiaSchema.Edge build() {
        gaia.schema.GaiaSchema.Edge result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gaia.schema.GaiaSchema.Edge buildPartial() {
        gaia.schema.GaiaSchema.Edge result = new gaia.schema.GaiaSchema.Edge(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.gid_ = gid_;
        result.label_ = label_;
        result.in_ = in_;
        result.out_ = out_;
        result.properties_ = internalGetProperties();
        result.properties_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gaia.schema.GaiaSchema.Edge) {
          return mergeFrom((gaia.schema.GaiaSchema.Edge)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gaia.schema.GaiaSchema.Edge other) {
        if (other == gaia.schema.GaiaSchema.Edge.getDefaultInstance()) return this;
        if (!other.getGid().isEmpty()) {
          gid_ = other.gid_;
          onChanged();
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        if (!other.getIn().isEmpty()) {
          in_ = other.in_;
          onChanged();
        }
        if (!other.getOut().isEmpty()) {
          out_ = other.out_;
          onChanged();
        }
        internalGetMutableProperties().mergeFrom(
            other.internalGetProperties());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gaia.schema.GaiaSchema.Edge parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gaia.schema.GaiaSchema.Edge) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object gid_ = "";
      /**
       * <code>optional string gid = 1;</code>
       */
      public java.lang.String getGid() {
        java.lang.Object ref = gid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGidBytes() {
        java.lang.Object ref = gid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gid = 1;</code>
       */
      public Builder setGid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gid = 1;</code>
       */
      public Builder clearGid() {
        
        gid_ = getDefaultInstance().getGid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gid = 1;</code>
       */
      public Builder setGidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 2;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object in_ = "";
      /**
       * <code>optional string in = 3;</code>
       */
      public java.lang.String getIn() {
        java.lang.Object ref = in_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          in_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string in = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInBytes() {
        java.lang.Object ref = in_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          in_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string in = 3;</code>
       */
      public Builder setIn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        in_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string in = 3;</code>
       */
      public Builder clearIn() {
        
        in_ = getDefaultInstance().getIn();
        onChanged();
        return this;
      }
      /**
       * <code>optional string in = 3;</code>
       */
      public Builder setInBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        in_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object out_ = "";
      /**
       * <code>optional string out = 4;</code>
       */
      public java.lang.String getOut() {
        java.lang.Object ref = out_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          out_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string out = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOutBytes() {
        java.lang.Object ref = out_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          out_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string out = 4;</code>
       */
      public Builder setOut(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        out_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string out = 4;</code>
       */
      public Builder clearOut() {
        
        out_ = getDefaultInstance().getOut();
        onChanged();
        return this;
      }
      /**
       * <code>optional string out = 4;</code>
       */
      public Builder setOutBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        out_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> properties_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetProperties() {
        if (properties_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PropertiesDefaultEntryHolder.defaultEntry);
       }
        return properties_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableProperties() {
        onChanged();;
        if (properties_ == null) {
          properties_ = com.google.protobuf.MapField.newMapField(
              PropertiesDefaultEntryHolder.defaultEntry);
        }
        if (!properties_.isMutable()) {
          properties_ = properties_.copy();
        }
        return properties_;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 5;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String> getProperties() {
        return internalGetProperties().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 5;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableProperties() {
        return internalGetMutableProperties().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 5;</code>
       */
      public Builder putAllProperties(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableProperties().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gaia.schema.Edge)
    }

    // @@protoc_insertion_point(class_scope:gaia.schema.Edge)
    private static final gaia.schema.GaiaSchema.Edge DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gaia.schema.GaiaSchema.Edge();
    }

    public static gaia.schema.GaiaSchema.Edge getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Edge>
        PARSER = new com.google.protobuf.AbstractParser<Edge>() {
      public Edge parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Edge(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Edge> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Edge> getParserForType() {
      return PARSER;
    }

    public gaia.schema.GaiaSchema.Edge getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gaia_schema_Vertex_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gaia_schema_Vertex_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gaia_schema_Vertex_PropertiesEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gaia_schema_Vertex_PropertiesEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gaia_schema_Edge_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gaia_schema_Edge_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gaia_schema_Edge_PropertiesEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gaia_schema_Edge_PropertiesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0core/src/main/proto/gaia/schema/GaiaSc" +
      "hema.proto\022\013gaia.schema\"\220\001\n\006Vertex\022\013\n\003gi" +
      "d\030\001 \001(\t\022\r\n\005label\030\002 \001(\t\0227\n\nproperties\030\003 \003" +
      "(\0132#.gaia.schema.Vertex.PropertiesEntry\032" +
      "1\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001\"\245\001\n\004Edge\022\013\n\003gid\030\001 \001(\t\022\r\n\005labe" +
      "l\030\002 \001(\t\022\n\n\002in\030\003 \001(\t\022\013\n\003out\030\004 \001(\t\0225\n\nprop" +
      "erties\030\005 \003(\0132!.gaia.schema.Edge.Properti" +
      "esEntry\0321\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gaia_schema_Vertex_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gaia_schema_Vertex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gaia_schema_Vertex_descriptor,
        new java.lang.String[] { "Gid", "Label", "Properties", });
    internal_static_gaia_schema_Vertex_PropertiesEntry_descriptor =
      internal_static_gaia_schema_Vertex_descriptor.getNestedTypes().get(0);
    internal_static_gaia_schema_Vertex_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gaia_schema_Vertex_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_gaia_schema_Edge_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gaia_schema_Edge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gaia_schema_Edge_descriptor,
        new java.lang.String[] { "Gid", "Label", "In", "Out", "Properties", });
    internal_static_gaia_schema_Edge_PropertiesEntry_descriptor =
      internal_static_gaia_schema_Edge_descriptor.getNestedTypes().get(0);
    internal_static_gaia_schema_Edge_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_gaia_schema_Edge_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
