#!/bin/bash

BDIR=$(cd $(dirname $0); pwd)


num_jars=$(ls "$BDIR"/core/target/scala-*/ | grep "gaia-core-assembly-.*.jar" | wc -l)

function check_jar {
if [ "$num_jars" -eq "0" ]; then
    echo "Failed to find BMEG assembly" >&2
    echo "You need to build the GAIA tools with 'sbt/sbt assembly' before running this program." >&2
    exit 1
fi
GAIA_BUILD_JAR=`ls $BDIR/core/target/scala-*/gaia-core-assembly-*.jar | head -n1`
GAIA_MEM="-Xmx4g"
GAIA_BASE_CMD="java $GAIA_MEM -cp $GAIA_BUILD_JAR"
}


CMD=$1
shift

case $CMD in
build)
export JAVA_OPTS="-Xms256m -Xmx4g"
sbt assembly
;;
load) 
check_jar
$GAIA_BASE_CMD gaia.app.Import $@ 
;;
esac
