#!/usr/bin/env python

import sys
from os import listdir
from os.path import isfile, join, exists
import subprocess

if __name__ == '__main__':
    match = sys.argv[1]
    srcs = [d + '/src/' + layer + '/scala' for d in listdir('.') if not isfile(d) and 'src' in listdir(d) for layer in ['main', 'test']]
    command = ['grep', '-Rni', match] + filter(lambda src: exists(src), srcs)
    print(' '.join(command))

    try:
        result = subprocess.check_output(command)
        print(result)
    except subprocess.CalledProcessError, e:
        print(e.output)